apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: chat-app-rhoai 
  janus-idp.io/tekton: chat-app-rhoai
  backstage.io/kubernetes-id: chat-app-rhoai
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: chat-app-rhoai
resources: 
- application-dev.yaml