apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: chat-app-rhoai
  janus-idp.io/tekton: chat-app-rhoai
  backstage.io/kubernetes-id: chat-app-rhoai
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: chat-app-rhoai
resources: 
- initialize-namespace.yaml
- pvc.yaml
- deployment-model-server.yaml
- service-model-server.yaml
- deployment.yaml
- route.yaml
- service.yaml
- rhoai/